export enum ApiErrorCodes {
  GENERATION_IN_PROGRESS = 'GENERATION_IN_PROGRESS',
  GENERATION_NOT_FOUND = 'GENERATION_NOT_FOUND',
  GENERATOR_REQUIRED = 'GENERATOR_REQUIRED',
  GRAPH_CHANGED = 'GRAPH_CHANGED',
  GRAPH_VERSION_CONFLICT = 'GRAPH_VERSION_CONFLICT',
  IDEMPOTENCY_CONFLICT = 'IDEMPOTENCY_CONFLICT',
  INCOMPLETE_CHAIN = 'INCOMPLETE_CHAIN',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  INVALID_GRAPH = 'INVALID_GRAPH',
  INVALID_JSON = 'INVALID_JSON',
  PAYLOAD_TOO_LARGE = 'PAYLOAD_TOO_LARGE',
  PRECONDITION_FAILED = 'PRECONDITION_FAILED',
  PRECONDITION_REQUIRED = 'PRECONDITION_REQUIRED',
  ROUTE_NOT_FOUND = 'ROUTE_NOT_FOUND',
  SPACE_NOT_FOUND = 'SPACE_NOT_FOUND',
  UNSUPPORTED_MEDIA_TYPE = 'UNSUPPORTED_MEDIA_TYPE',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
}

/** failureCode тестового отказа генерации: это состояние операции, а не ошибка транспорта. */
export const SIMULATED_FAILURE = 'SIMULATED_FAILURE';
